# Generated by Django 4.0.4 on 2022-05-12 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0002_rename_complated_todo_completed_todo_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todo',
            options={'ordering': ['completed']},
        ),
    ]
